config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  post 'degrees/upload_logs' => 'degrees#upload_logs'

  resources :fields
  resources :probes
  resources :degrees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/degree.rb
class Degree < ApplicationRecord
  belongs_to :probe
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :probes
end

app/models/probe.rb
class Probe < ApplicationRecord
  belongs_to :field
  has_many :degrees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  layout 'application'
  def new
    @probe = Probe.find(params[:probe_id])
  end

  def upload_logs
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    puts "xxxxxxxxx"
    if params[:file].present? && !params[:file].blank?
      data = SmarterCSV.process(params[:file].path)
      data.each do |row|
        timestamp = DateTime.parse(row[:date])
        log = Degree.find_or_create_by(:probe_id => params[:probe_id],:created_at => timestamp.beginning_of_hour,)
        log.reading = row[:degree]
        if log.reading < 1.4
          log.cold_units_utah = 0
        elsif log.reading < 2.5
          log.cold_units_utah = 0.5
        elsif log.reading <= 9
          log.cold_units_utah = 1
        elsif log.reading < 12.6
          log.cold_units_utah = 0.5
        elsif log.reading < 16
          log.cold_units_utah = 0
        elsif log.reading <= 18
          log.cold_units_utah = -0.5
        elsif log.reading > 18
          log.cold_units_utah = -1
        end
        log.save!
      end
      flash[:success] = 'file uploaded and processed'
      redirect_to :action => 'new', :probe_id => params[:probe_id]
    else
      flash[:error] = 'No file uploaded'
      redirect_to :action => 'new', :probe_id => params[:probe_id]
    end

  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  layout 'application'
  def index
    @fields = Field.order('size DESC')
  end

  def new
    @field = Field.new

  end

  def create
    @field = Field.new(field_params)
    if @field.save
      redirect_to :action => 'show', :id => @field.id
    else
      render 'new'
    end
  end

  def show
    @field = Field.find(params[:id])
    @chill_begin_date = Date.parse("15-05-#{Date.today.year}")
    @chill_end_date = Date.parse("30-08-#{Date.today.year}")
    @chill_units_by_probe = Degree.joins(:probe).where('degrees.created_at BETWEEN ? AND ? AND probes.field_id = ?',@chill_begin_date,@chill_end_date,@field.id).group('degrees.probe_id').select('degrees.probe_id, SUM(cold_units_utah) as chill_units')
  end

  def edit
    @field = Field.find(params[:id])
  end

  def update
    @field = Field.find(params[:id])
    if @field.update(field_params)
      redirect_to @field
    else
      render 'edit'
    end
  end
  private

  def field_params
    params.require(:field).permit(:name,:field_polygon, :latitude, :longitude)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'
  def index
  end
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController
  layout 'application'

  def index
    @probes = Probe.order('field_id DESC')
    @fields = Field.all
  end

  def new
    @field = Field.find(params[:field_id])
    @probe = Probe.new
    @probe.field_id = @field.id
  end

  def create
     @probe = Probe.new(probe_params)
     @field = Field.find(@probe.field_id)
    if @probe.save
      redirect_to :action => 'show', :id => @probe.id
    else
     render 'new'
    end
  end

  def show
    @probe = Probe.find(params[:id])
    @chill_begin_date = Date.parse("15-05-#{Date.today.year}")
    @chill_end_date = Date.parse("30-08-#{Date.today.year}")
    @chill_units_range = @probe.degrees.where('degrees.created_at BETWEEN ? AND ?',@chill_begin_date,@chill_end_date)
  end

  def edit
    @probe = Probe.find(params[:id])
    @field = Field.find(@probe.field_id)
  end

  def update
    @probe = Probe.find(params[:id])
    if @probe.update(probe_params)
      redirect_to @probe
    else
      render 'edit'
    end
  end

  private

  def probe_params
    params.require(:probe).permit(:name,:field_id, :latitude, :longitude, :elevation, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/views/degrees/new.html.erb
<%= link_to "VIEW #{@probe.name}", {:controller => 'probes', :action => 'show', :id => @probe.id}, :class => 'btn-blue btn-large' %>
<h2>UPLOAD TEMPRATURE LOGS FOR <%= @probe.name.upcase %></h2>

<div style="width: 40%">

  <%= form_tag({:controller =>'degrees', :action => 'upload_logs', :probe_id => @probe.id},:multipart => true ) do %>

      <div>Headers required date,degree</div>

      <label>Upload CSV</label>
      <%= file_field_tag :file, :class => 'btn-black'%>

      <%= submit_tag "Upload File", :class => 'btn-black' %>

  <% end %>
  <h4>Calculation Postive Chill Units (UTAH MODEL)</h4>
  <table style="width: 40%">
    <tr style="text-align: center; font-weight:bold; font-size:12px; line-height:30px; border-bottom:1px solid #333333">
      <td>Hourly Temp</td>
      <td>Weighted Unit</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td>< 1.4</td>
      <td>0</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td>1.5 - 2.4</td>
      <td>0.5</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td>2.5 - 9.1</td>
      <td>1.0</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td>9.2 - 12.4</td>
      <td>0.5</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td>12.5 - 15.9</td>
      <td>0</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td>16 - 18</td>
      <td>-0.5</td>
    </tr>
    <tr style="text-align: center; font-size:16px; line-height:30px; border-bottom:1px solid #333">
      <td> > 18</td>
      <td>-1.0</td>
    </tr>
  </table>

</div>

app/views/fields/edit.html.erb
<h1>UPDATE : <%= @field.name.upcase %></h1>


<div style="float:right; width:50%; margin-right:5%">
  <label>Enter Name/Address for Distributor</label>
   <div class="form-input-group"> <input id="pac-input" class="form-input-element" type="text" placeholder="Enter a location" style="width:100%"></div>  

  <div id="map" style="width:100%; height:500px; background-color:F2F2F2"></div>
</div>


<div>
  <%= form_for(@field) do |f| %>
      <%= f.hidden_field :field_polygon %>
      <%= f.hidden_field :longitude %>
      <%= f.hidden_field :latitude %>
      <%= f.label :name %>
      <%= f.text_field :name, :style => '400px' %>

      <div><%= f.submit "Update Field", class: "btn-black" %></div>
  <% end %>

</div>













<script>
    function initMap() {
        var polygon;
        var default_position = {lat: -26.8746024, lng: 24.6939132};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 5,
            center: default_position
        });


        // -- if existing data --
    <% if @field && @field.longitude.to_f != 0 && @field.latitude.to_f != 0 %>
        var location_marker = 	{lat: <%= @field.latitude %>, lng: <%= @field.longitude %>};
      /* recenter map */
        map.setCenter( location_marker);
        map.zoom = 8;
      /* drop address marker */
        var marker_address = new google.maps.Marker({ position: location_marker, map: map});

    <% if @field.field_polygon.to_s.length > 20 %>
        add_polygon(<%= @field.latitude %>,<%= @field.longitude %>);
    <% else %>
        create_polygon(<%= @field.latitude %>,<%= @field.longitude %>);
    <% end %>

        <% end %>

        var input = (document.getElementById('pac-input'));

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
            map: map,
            anchorPoint: new google.maps.Point(0, -29)
        });





        var input = (document.getElementById('pac-input'));

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
            map: map,
            anchorPoint: new google.maps.Point(0, -29)
        });




        autocomplete.addListener('place_changed', function() {
            infowindow.close();
            marker.setVisible(false);
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                window.alert("Autocomplete's returned place contains no geometry");
                return;
            }

            // If the place has a geometry, then present it on a map.
            if (place.geometry.viewport) {
                map.fitBounds(place.geometry.viewport);
            } else {
                map.setCenter(place.geometry.location);
                map.setZoom(9);  // Why 17? Because it looks good.
            }
            marker.setIcon(/** @type {google.maps.Icon} */({
                url: place.icon,
                size: new google.maps.Size(71, 71),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(17, 34),
                scaledSize: new google.maps.Size(35, 35)
            }));


            create_polygon(place.geometry.location.lat(),place.geometry.location.lng());

            document.getElementById("field_latitude").value = place.geometry.location.lat();
            document.getElementById("field_longitude").value = place.geometry.location.lng();



            //

            marker.setPosition(place.geometry.location);
            marker.setVisible(true);

            var address = '';
            if (place.address_components) {
                address = [
                    (place.address_components[0] && place.address_components[0].short_name || ''),
                    (place.address_components[1] && place.address_components[1].short_name || ''),
                    (place.address_components[2] && place.address_components[2].short_name || '')
                ].join(' ');
            }


            var street_number = "";
            var street_name = "";
            var suburb = "";
            var city = "";
            var province = "";
            var country = "";
            var code = "";
            console.log(place)
            for (var i = 0; i < place.address_components.length; i++) {
                var addressType = place.address_components[i].types[0];
                if (addressType == 'street_number') {
                    street_number = place.address_components[i].short_name;
                } else if (addressType == 'route') {
                    street_name = place.address_components[i].short_name;
                } else if (addressType == 'sublocality_level_2') {
                    suburb = place.address_components[i].short_name;
                } else if (addressType == 'locality') {
                    city = place.address_components[i].short_name;
                } else if (addressType == 'administrative_area_level_1') {
                    province = place.address_components[i].short_name;
                } else if (addressType == 'country') {
                    country = place.address_components[i].short_name;
                } else if (addressType == 'postal_code') {
                    code = place.address_components[i].short_name;
                }

            }

            //document.getElementById("destination_address_street").value = street_number + ' ' + street_name + ' ' + suburb;
            //document.getElementById("destination_address_code").value = code;
            //document.getElementById("destination_address_city").value = city;
            $('#street').html('Street : ' + street_number + ' ' + street_name + ' ' + suburb);
            $('#city').html('City : ' + city);
            $('#code').html('Code : ' + code);







        });


        function create_polygon(lat,lng) {
            console.log('set polygon');
            var polygon_path = [
                {lat: lat + 0.2, lng: lng - 0.2},
                {lat: lat + 0.2, lng: lng + 0.2},
                {lat: lat - 0.2, lng: lng + 0.2},
                {lat: lat - 0.2, lng: lng - 0.2}
            ];

            // Define a rectangle and set its editable property to true.
            polygon = new google.maps.Polygon({
                paths: polygon_path,
                editable: true,
                draggable: true,
                geodesic: true
            });
            polygon.setMap(map);

            google.maps.event.addListener(polygon.getPath(), 'set_at', function(event) {
                save_polygon();
            });

            google.maps.event.addListener(polygon.getPath(), 'insert_at', function(event) {
                save_polygon();
            });
        };

        function add_polygon() {


            var polygon_array = JSON.parse('<%= @field.field_polygon.inspect.gsub('"','') %>');
            var polygon_path =[];
            for(var i=0; i<polygon_array.length; i++) {
                polygon_path.push(new google.maps.LatLng(polygon_array[i][0], polygon_array[i][1]));
                console.log(polygon_array[i][0]);
                console.log(polygon_array[i][1]);
            }

            // Define a rectangle and set its editable property to true.
            polygon = new google.maps.Polygon({
                paths: polygon_path,
                editable: true,
                draggable: true,
                geodesic: true
            });
            polygon.setMap(map);

            google.maps.event.addListener(polygon.getPath(), 'set_at', function(event) {
                save_polygon();
            });

            google.maps.event.addListener(polygon.getPath(), 'insert_at', function(event) {
                save_polygon();
            });
        };

        function save_polygon() {
            console.log('hello');

            var vertices = polygon.getPath(); // MVCArray

            var pointsArray = []; //list of polyline points
            for (var i =0; i < vertices.getLength(); i++) {
                var xy = vertices.getAt(i); //LatLang for a polyline
                var item = [xy.lat(),xy.lng()];
                console.log(xy.lat());
                console.log(xy.lng());
                pointsArray.push(item);
            }
            document.getElementById("field_field_polygon").value = JSON.stringify(pointsArray);
        };








    }









</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB3jjoMddEPVxI1Z8IboGf_UDPIS6UjJBw&libraries=places&callback=initMap"> </script>





<!-- plus and minus button for checkout -->

app/views/fields/index.html.erb
<h1>FIELDS</h1>
<%= link_to "NEW FIELD", new_field_path, :class => 'btn-blue btn-large' %>

<table cellpadding="0" cellspacing="0">
  <tr>
    <th>FIELD NAME</th>
    <th>SIZA</th>
    <th>PROBES</th>
    <th></th>
  </tr>
  <% @fields.each do |field| %>
    <tr>
      <td style="text-align: left"><%= field.name %></td>
      <td><%= field.size %></td>
      <td><%= field.probes.count %></td>
      <td><%= link_to "VIEW", {:controller => 'fields', :action => 'show', :id => field.id}, :class => 'btn-black btn-mini' %></td>
    </tr>
  <% end %>

</table>

app/views/fields/new.html.erb
<h2>Create New Field</h2>

<%= form_for(@field) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%#= f.label :email %>
    <%#= f.email_field :email %>

    <%#= f.label :password %>
    <%#= f.password_field :password %>

    <%#= f.label :password_confirmation, "Confirmation" %>
    <%#= f.password_field :password_confirmation %>

    <%= f.submit "Create Field", class: "btn-black" %>
<% end %>

app/views/fields/show.html.erb
<h2>FIELD : <%= @field.name.upcase %></h2>


<%= link_to "UPDATE FIELD INFO", {:controller =>'fields', :action => 'edit', :field_id => @field.id}, :class => 'btn-blue btn-large' %>



<div style="width:48%; float:right">
<h4>PROBES</h4>
  <%= link_to "NEW PROBE", {:controller =>'probes', :action => 'new', :field_id => @field.id}, :class => 'btn-blue btn-large' %>
<table cellspacing="0" cellpadding="0">
  <tr>
    <th>NAME</th>
    <th>READINGS</th>
    <th>PERIOD</th>
    <th></th>
  </tr>
  <% @field.probes.each do |probe| %>
  <tr>
    <td style="text-align: left"><%= probe.name %></td>
    <% if probe.degrees.count > 0 %>
      <td><%= probe.degrees.count %></td>
      <td><%= probe.degrees.order('created_at ASC').first.created_at.strftime('%d %b %Y') %> - <%= probe.degrees.order('created_at ASC').last.created_at.strftime('%d %b %Y') %></td>
    <% else %>
        <td>0</td>
        <td>No Readings Uploaded</td>
    <% end %>
    <td  style="text-align: right">
      <%= link_to "UPLOAD", {:controller => 'degrees', :action => 'new', :probe_id => probe.id}, :class => 'btn-black btn-mini' %>
      <%= link_to "VIEW", {:controller => 'probes', :action => 'show', :id => probe.id}, :class => 'btn-black btn-mini' %></td>
  </tr>
  <% end %>
</table>
</div>

<div style="width:50%;">
  <div id="map" style="width:100%; height:500px; background-color:F2F2F2"></div>
</div>

<div style="margin:50px 0">
  <h2>CHILL UNIT OVERVIEW - <%= @chill_begin_date.strftime('%d %b %Y').upcase %> - <%= @chill_end_date.strftime('%d %b %Y').upcase %></h2>
  <div style="float:right; width:60%">
    <h3>POSITIVE CHILL UNITS BY MONTH (UTAH MODEL)</h3>
    <%= column_chart @field.probes.map { |probe|
      {name: "#{probe.field.name} -#{probe.name}", data: Degree.where('created_at BETWEEN ? AND ? AND probe_id = ?',@chill_begin_date,@chill_end_date,probe.id).group_by_month(:created_at).sum(:cold_units_utah)}
    } %>
  </div>

  <div style="width: 38%; margin-right:2%">
    <h3>ACCUMULATED CHILL UNITS</h3>
    <div></div>
    <table cellpadding="0" cellspacing="0">
      <tr>
        <th>PROBE</th>
        <th>PST UTAH CHILL UNITS</th>
        <th>UTAH CHILL UNITS</th>
        <th>< 7.2&#8451 CHILL UNITS</th>
      </tr>
      <% @chill_units_by_probe.each do |obj| %>
        <tr>
          <td style="text-align: left"><%= obj.probe.name %></td>
          <td><b><%= obj.chill_units %></b></td>
          <td><%= obj.probe.degrees.where('created_at BETWEEN ? AND ? AND cold_units_utah > ?',@chill_begin_date,@chill_end_date,0).sum(:cold_units_utah) %></td>
          <td><%= obj.probe.degrees.where('created_at BETWEEN ? AND ? AND reading < ?',@chill_begin_date,@chill_end_date,7.2).count %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div style="margin:50px 0; clear:both; padding-top:100px">
  <h3>MAKSIMUM TEMPRATURE</h3>
  <%= line_chart @field.probes.map { |probe|
    {name: "#{probe.name}", data: Degree.where(:probe_id => probe.id).group_by_day(:created_at).maximum(:reading)}
  } %>
</div>

<div style="margin:50px 0">
  <h3>MINIMUM TEMPRATURE</h3>
  <%= line_chart @field.probes.map { |probe|
    {name: "#{probe.name}", data: Degree.where(:probe_id => probe.id).group_by_day(:created_at).minimum(:reading)}
  } %>
</div>

<h3>DAILY CHILL UNITS (UTAH MODEL)</h3>
<%= column_chart @field.probes.map { |probe|
  {name: "#{probe.name}", data: Degree.where('created_at BETWEEN ? AND ? AND probe_id = ?',@chill_begin_date,@chill_end_date,probe.id).group_by_day(:created_at).sum(:cold_units_utah)}
} %>














<script>
    function initMap() {
        var polygon;
        var default_position = {lat: -26.8746024, lng: 24.6939132};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 1,
            center: default_position
        });


        // -- if existing data --
    <% if @field.field_polygon.to_s.length > 20 %>
        //var location_marker = 	{lat: <%= @field.latitude %>, lng: <%= @field.longitude %>};
      /* recenter map */
        /* map.setCenter( location_marker); */
        map.zoom = 15;
        map.setMapTypeId('satellite');
      /* drop address marker */
       // var marker_address = new google.maps.Marker({ position: location_marker, map: map});

        add_polygon(<%= @field.latitude %>,<%= @field.longitude %>);







        <% @field.probes.each do |probe| %>

        var contentString = "<h4><%= probe.name %></h4><%= probe.description %> <p>Chill Units '<%= Date.today.year %>: <%= Degree.where('probe_id = ? AND YEAR(created_at) = ? AND MONTH(created_at) > ? AND MONTH(created_at) < ?',probe.id,Date.today.year,4,9).sum(:cold_units_utah) %></p> <p><a href='/probes/<%= probe.id %>', class='btn-black btn-mini'>VIEW</a></p>";

        var infowindow = new google.maps.InfoWindow({
            content: contentString,
        });




          var marker_position = {lat: <%= probe.latitude %>, lng: <%= probe.longitude %>};
          var marker = new google.maps.Marker({
              position: marker_position,
              label: '<%= probe.name %>',
              map: map,
          });
          marker.addListener('click', function() {
              infowindow.open(map, marker);
              //window.location.href = '/probes/<%= probe.id %>';
          });
        <% end %>

        var input = (document.getElementById('pac-input'));

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        //var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
            map: map,
            anchorPoint: new google.maps.Point(0, -29)
        });




/*
        var input = (document.getElementById('pac-input'));

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
            map: map,
            anchorPoint: new google.maps.Point(0, -29)
        });

*/


        autocomplete.addListener('place_changed', function() {
           // infowindow.close();
            marker.setVisible(false);
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                window.alert("Autocomplete's returned place contains no geometry");
                return;
            }

            // If the place has a geometry, then present it on a map.
            if (place.geometry.viewport) {
                map.fitBounds(place.geometry.viewport);
            } else {
                map.setCenter(place.geometry.location);
                map.setZoom(9);  // Why 17? Because it looks good.
            }
            marker.setIcon(/** @type {google.maps.Icon} */({
                url: place.icon,
                size: new google.maps.Size(71, 71),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(17, 34),
                scaledSize: new google.maps.Size(35, 35)
            }));


            create_polygon(place.geometry.location.lat(),place.geometry.location.lng());

            document.getElementById("field_latitude").value = place.geometry.location.lat();
            document.getElementById("field_longitude").value = place.geometry.location.lng();



            //

            marker.setPosition(place.geometry.location);
            marker.setVisible(true);

            var address = '';
            if (place.address_components) {
                address = [
                    (place.address_components[0] && place.address_components[0].short_name || ''),
                    (place.address_components[1] && place.address_components[1].short_name || ''),
                    (place.address_components[2] && place.address_components[2].short_name || '')
                ].join(' ');
            }


            var street_number = "";
            var street_name = "";
            var suburb = "";
            var city = "";
            var province = "";
            var country = "";
            var code = "";
            console.log(place)
            for (var i = 0; i < place.address_components.length; i++) {
                var addressType = place.address_components[i].types[0];
                if (addressType == 'street_number') {
                    street_number = place.address_components[i].short_name;
                } else if (addressType == 'route') {
                    street_name = place.address_components[i].short_name;
                } else if (addressType == 'sublocality_level_2') {
                    suburb = place.address_components[i].short_name;
                } else if (addressType == 'locality') {
                    city = place.address_components[i].short_name;
                } else if (addressType == 'administrative_area_level_1') {
                    province = place.address_components[i].short_name;
                } else if (addressType == 'country') {
                    country = place.address_components[i].short_name;
                } else if (addressType == 'postal_code') {
                    code = place.address_components[i].short_name;
                }

            }

            //document.getElementById("destination_address_street").value = street_number + ' ' + street_name + ' ' + suburb;
            //document.getElementById("destination_address_code").value = code;
            //document.getElementById("destination_address_city").value = city;
            $('#street').html('Street : ' + street_number + ' ' + street_name + ' ' + suburb);
            $('#city').html('City : ' + city);
            $('#code').html('Code : ' + code);







        });




        function add_polygon() {


            var polygon_array = JSON.parse('<%= @field.field_polygon.inspect.gsub('"','') %>');
            var polygon_path =[];
            for(var i=0; i<polygon_array.length; i++) {
                polygon_path.push(new google.maps.LatLng(polygon_array[i][0], polygon_array[i][1]));
                console.log(polygon_array[i][0]);
                console.log(polygon_array[i][1]);
                var pol_lat = polygon_array[i][0];
                var pol_lng = polygon_array[i][1];
            }

            // Define a rectangle and set its editable property to true.
            polygon = new google.maps.Polygon({
                paths: polygon_path,
                editable: false,
                draggable: false,
                geodesic: true
            });
            polygon.setMap(map);
            //var pol_lat = polygon.my_getBounds().getCenter().lat();
            //var pol_lng = polygon.my_getBounds().getCenter().lng();
            console.log(pol_lat);
            console.log(pol_lng);
            console.log('----------------------------');
            var marker = 	{lat: pol_lat, lng: pol_lng};
          /* recenter map */
            map.setCenter( marker);
        };










    }



    <% else %>
    <% end %>





</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB3jjoMddEPVxI1Z8IboGf_UDPIS6UjJBw&libraries=places&callback=initMap"> </script>





<!-- plus and minus button for checkout -->

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uitdraai</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>

        <div id="mobile-nav"></div>
        <nav>
          <ul class="menu">
            <li><a href="#">Home</a></li>
            <li><%= link_to "FIELDS", fields_path %></li>
            <li><%= link_to "PROBES", probes_path %></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </nav>

  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <div style="clear:both; margin-top:50px"><%= yield %></div>

  <%#= debug(params) if Rails.env.development? %>

  </div>
  <script type="text/javascript">
      $('#mobile-nav').click(function(event) {
          $('nav').toggleClass('active');
      });
  </script>


  </body>
</html>

app/views/probes/edit.html.erb
<h1>UPDATE : <%= @probe.name.upcase %> - FIELD : <%= @probe.field.name %></h1>

<%= render :partial => 'form' %>

app/views/probes/new.html.erb
<h2>ADD NEW PROBE FOR FIELD : <%= @field.name.upcase %></h2>


<%= render :partial => 'form' %>